---
layout: cv
title: Sierra Bond's CV
---
# Sierra Bond
Accountant, Student, Friend.

<div id="webaddress">
<a href="sierrambond@gmail.com">sierrambond@gmail.com</a>

## Currently

Applying to grad programs and jobs

### Specialized in

Planning and overseeing events, managing time effectively, using Excel spreadsheets and code in VBA, querying databases using mySQL, using HTML, CSS, and Java Script, basic skills in python, make visuals with Tableau and Power BI, staying motivated, being reliable, being organized, problem solving, leading, being an active listener, communicating efficiently with peers, being understanding, able to take constructive criticism, and working well as an individual but also in a team environment.

### Research interests

Plants, tax credits, pickleball, colleges, jobs.

## Education

`September 2021 - July 2025`
__Brigham Young University-Idaho, Idaho.__

- Pursuing a degree in accounting with a data science certificate and an emphasis in computer information
- Member of Student Accounting Society, volunteered at the school’s tax center (February 2025-April 2025)

## Awards

`2024`
MyEducator certificate of achievement for satisfactory completion of the MySQL course

`2021`
Seal of Biliteracy Award - Spanish language at both the State and Global level

`2020 - 2021`
Member of National Honor Society and Spanish National Honor Society

## Occupation

__Team Member at Culver's__, Idaho Falls, ID
`October 2023 - Now`

- Greeted guests with a smile which ensured they felt welcome when they ordered and then took their orders quickly
- Streamlined drive-thru orders during peak hours, boosting accuracy by 34% while addressing special requests
- Delegated front of house tasks ensuring food items went out at or under the corporate standard time
- Ensured guest satisfaction by checking in with diners, addressing concerns promptly, and resolving issues

__Head Tax Intern at Crandall & Oseen PAs__, Idaho Falls, ID
`January - April 2023, February - April 2022`

- Processed an average of 250 tax returns per busy season, ensuring fast and accurate data entry to meet deadlines
- Reviewed and revised preliminary tax returns with CPAs, incorporating feedback to ensure accuracy and compliance
- Contacted clients to obtain missing information, ensuring timely completion of returns before the tax deadline

__Crew Member at Little Caesar's__, Rexburg, ID
`August 2022 - July 2023`

- Efficiently greeted customers and operated the cash register, reducing wait times by 18% during busy rushes
- Meticulously followed custom order details to ensure customer satisfaction and loyalty
- Maintained precision in repetitive tasks to uphold high standards and the company’s reputation



<!-- ### Footer -->

Last updated: April 2025